/** 所有省份下的市 */
export const $city = {
    北京: [
        { value: '东城', label: '东城' },
        { value: '西城', label: '西城' },
        { value: '朝阳', label: '朝阳' },
        { value: '丰台', label: '丰台' },
        { value: '石景山', label: '石景山' },
        { value: '海淀', label: '海淀' },
        { value: '门头沟', label: '门头沟' },
        { value: '房山', label: '房山' },
        { value: '通州', label: '通州' },
        { value: '顺义', label: '顺义' },
        { value: '昌平', label: '昌平' },
        { value: '大兴', label: '大兴' },
        { value: '怀柔', label: '怀柔' },
        { value: '平谷', label: '平谷' },
        { value: '密云', label: '密云' },
        { value: '延庆', label: '延庆' }
    ],
    天津: [
        { value: '和平', label: '和平' },
        { value: '河东', label: '河东' },
        { value: '河西', label: '河西' },
        { value: '南开', label: '南开' },
        { value: '河北', label: '河北' },
        { value: '红桥', label: '红桥' },
        { value: '东丽', label: '东丽' },
        { value: '西青', label: '西青' },
        { value: '津南', label: '津南' },
        { value: '北辰', label: '北辰' },
        { value: '武清', label: '武清' },
        { value: '宝坻', label: '宝坻' },
        { value: '滨海', label: '滨海' },
        { value: '宁河', label: '宁河' },
        { value: '静海', label: '静海' },
        { value: '蓟州', label: '蓟州' }
    ],
    河北: [
        { value: '石家庄', label: '石家庄' },
        { value: '唐山', label: '唐山' },
        { value: '秦皇岛', label: '秦皇岛' },
        { value: '邯郸', label: '邯郸' },
        { value: '邢台', label: '邢台' },
        { value: '保定', label: '保定' },
        { value: '张家口', label: '张家口' },
        { value: '承德', label: '承德' },
        { value: '沧州', label: '沧州' },
        { value: '廊坊', label: '廊坊' },
        { value: '衡水', label: '衡水' }
    ],
    山西: [
        { value: '太原', label: '太原' },
        { value: '大同', label: '大同' },
        { value: '阳泉', label: '阳泉' },
        { value: '长治', label: '长治' },
        { value: '晋城', label: '晋城' },
        { value: '朔州', label: '朔州' },
        { value: '晋中', label: '晋中' },
        { value: '运城', label: '运城' },
        { value: '忻州', label: '忻州' },
        { value: '临汾', label: '临汾' },
        { value: '吕梁', label: '吕梁' }
    ],
    内蒙古: [
        { value: '呼和浩特', label: '呼和浩特' },
        { value: '包头', label: '包头' },
        { value: '乌海', label: '乌海' },
        { value: '赤峰', label: '赤峰' },
        { value: '通辽', label: '通辽' },
        { value: '鄂尔多斯', label: '鄂尔多斯' },
        { value: '呼伦贝尔', label: '呼伦贝尔' },
        { value: '巴彦淖尔', label: '巴彦淖尔' },
        { value: '乌兰察布', label: '乌兰察布' },
        { value: '兴安盟', label: '兴安盟' },
        { value: '锡林郭勒盟', label: '锡林郭勒盟' },
        { value: '阿拉善盟', label: '阿拉善盟' }
    ],
    辽宁: [
        { value: '沈阳', label: '沈阳' },
        { value: '大连', label: '大连' },
        { value: '鞍山', label: '鞍山' },
        { value: '抚顺', label: '抚顺' },
        { value: '本溪', label: '本溪' },
        { value: '丹东', label: '丹东' },
        { value: '锦州', label: '锦州' },
        { value: '营口', label: '营口' },
        { value: '阜新', label: '阜新' },
        { value: '辽阳', label: '辽阳' },
        { value: '盘锦', label: '盘锦' },
        { value: '铁岭', label: '铁岭' },
        { value: '朝阳', label: '朝阳' },
        { value: '葫芦岛', label: '葫芦岛' }
    ],
    吉林: [
        { value: '长春', label: '长春' },
        { value: '吉林', label: '吉林' },
        { value: '四平', label: '四平' },
        { value: '辽源', label: '辽源' },
        { value: '通化', label: '通化' },
        { value: '白山', label: '白山' },
        { value: '松原', label: '松原' },
        { value: '白城', label: '白城' },
        { value: '延边', label: '延边' }
    ],
    黑龙江: [
        { value: '哈尔滨', label: '哈尔滨' },
        { value: '齐齐哈尔', label: '齐齐哈尔' },
        { value: '鸡西', label: '鸡西' },
        { value: '鹤岗', label: '鹤岗' },
        { value: '双鸭山', label: '双鸭山' },
        { value: '大庆', label: '大庆' },
        { value: '伊春', label: '伊春' },
        { value: '佳木斯', label: '佳木斯' },
        { value: '七台河', label: '七台河' },
        { value: '牡丹江', label: '牡丹江' },
        { value: '黑河', label: '黑河' },
        { value: '绥化', label: '绥化' },
        { value: '大兴安岭', label: '大兴安岭' }
    ],
    上海: [
        { value: '黄浦', label: '黄浦' },
        { value: '徐汇', label: '徐汇' },
        { value: '长宁', label: '长宁' },
        { value: '静安', label: '静安' },
        { value: '普陀', label: '普陀' },
        { value: '虹口', label: '虹口' },
        { value: '杨浦', label: '杨浦' },
        { value: '闵行', label: '闵行' },
        { value: '宝山', label: '宝山' },
        { value: '嘉定', label: '嘉定' },
        { value: '浦东', label: '浦东' },
        { value: '金山', label: '金山' },
        { value: '松江', label: '松江' },
        { value: '青浦', label: '青浦' },
        { value: '奉贤', label: '奉贤' },
        { value: '崇明', label: '崇明' }
    ],
    江苏: [
        { value: '南京', label: '南京' },
        { value: '无锡', label: '无锡' },
        { value: '徐州', label: '徐州' },
        { value: '常州', label: '常州' },
        { value: '苏州', label: '苏州' },
        { value: '南通', label: '南通' },
        { value: '连云港', label: '连云港' },
        { value: '淮安', label: '淮安' },
        { value: '盐城', label: '盐城' },
        { value: '扬州', label: '扬州' },
        { value: '镇江', label: '镇江' },
        { value: '泰州', label: '泰州' },
        { value: '宿迁', label: '宿迁' }
    ],
    浙江: [
        { value: '杭州', label: '杭州' },
        { value: '宁波', label: '宁波' },
        { value: '温州', label: '温州' },
        { value: '嘉兴', label: '嘉兴' },
        { value: '湖州', label: '湖州' },
        { value: '绍兴', label: '绍兴' },
        { value: '金华', label: '金华' },
        { value: '衢州', label: '衢州' },
        { value: '舟山', label: '舟山' },
        { value: '台州', label: '台州' },
        { value: '丽水', label: '丽水' }
    ],
    安徽: [
        { value: '合肥', label: '合肥' },
        { value: '芜湖', label: '芜湖' },
        { value: '蚌埠', label: '蚌埠' },
        { value: '淮南', label: '淮南' },
        { value: '马鞍山', label: '马鞍山' },
        { value: '淮北', label: '淮北' },
        { value: '铜陵', label: '铜陵' },
        { value: '安庆', label: '安庆' },
        { value: '黄山', label: '黄山' },
        { value: '滁州', label: '滁州' },
        { value: '阜阳', label: '阜阳' },
        { value: '宿州', label: '宿州' },
        { value: '六安', label: '六安' },
        { value: '亳州', label: '亳州' },
        { value: '池州', label: '池州' },
        { value: '宣城', label: '宣城' }
    ],
    福建: [
        { value: '福州', label: '福州' },
        { value: '厦门', label: '厦门' },
        { value: '莆田', label: '莆田' },
        { value: '三明', label: '三明' },
        { value: '泉州', label: '泉州' },
        { value: '漳州', label: '漳州' },
        { value: '南平', label: '南平' },
        { value: '龙岩', label: '龙岩' },
        { value: '宁德', label: '宁德' }
    ],
    江西: [
        { value: '南昌', label: '南昌' },
        { value: '景德镇', label: '景德镇' },
        { value: '萍乡', label: '萍乡' },
        { value: '九江', label: '九江' },
        { value: '新余', label: '新余' },
        { value: '鹰潭', label: '鹰潭' },
        { value: '赣州', label: '赣州' },
        { value: '吉安', label: '吉安' },
        { value: '宜春', label: '宜春' },
        { value: '抚州', label: '抚州' },
        { value: '上饶', label: '上饶' }
    ],
    山东: [
        { value: '济南', label: '济南' },
        { value: '青岛', label: '青岛' },
        { value: '淄博', label: '淄博' },
        { value: '枣庄', label: '枣庄' },
        { value: '东营', label: '东营' },
        { value: '烟台', label: '烟台' },
        { value: '潍坊', label: '潍坊' },
        { value: '济宁', label: '济宁' },
        { value: '泰安', label: '泰安' },
        { value: '威海', label: '威海' },
        { value: '日照', label: '日照' },
        { value: '临沂', label: '临沂' },
        { value: '德州', label: '德州' },
        { value: '聊城', label: '聊城' },
        { value: '滨州', label: '滨州' },
        { value: '菏泽', label: '菏泽' }
    ],
    河南: [
        { value: '郑州', label: '郑州' },
        { value: '开封', label: '开封' },
        { value: '洛阳', label: '洛阳' },
        { value: '平顶山', label: '平顶山' },
        { value: '安阳', label: '安阳' },
        { value: '鹤壁', label: '鹤壁' },
        { value: '新乡', label: '新乡' },
        { value: '焦作', label: '焦作' },
        { value: '濮阳', label: '濮阳' },
        { value: '许昌', label: '许昌' },
        { value: '漯河', label: '漯河' },
        { value: '三门峡', label: '三门峡' },
        { value: '南阳', label: '南阳' },
        { value: '商丘', label: '商丘' },
        { value: '信阳', label: '信阳' },
        { value: '周口', label: '周口' },
        { value: '驻马店', label: '驻马店' }
    ],
    湖北: [
        { value: '武汉', label: '武汉' },
        { value: '黄石', label: '黄石' },
        { value: '十堰', label: '十堰' },
        { value: '宜昌', label: '宜昌' },
        { value: '襄阳', label: '襄阳' },
        { value: '鄂州', label: '鄂州' },
        { value: '荆门', label: '荆门' },
        { value: '孝感', label: '孝感' },
        { value: '荆州', label: '荆州' },
        { value: '黄冈', label: '黄冈' },
        { value: '咸宁', label: '咸宁' },
        { value: '随州', label: '随州' },
        { value: '恩施', label: '恩施' }
    ],
    湖南: [
        { value: '长沙', label: '长沙' },
        { value: '株洲', label: '株洲' },
        { value: '湘潭', label: '湘潭' },
        { value: '衡阳', label: '衡阳' },
        { value: '邵阳', label: '邵阳' },
        { value: '岳阳', label: '岳阳' },
        { value: '常德', label: '常德' },
        { value: '张家界', label: '张家界' },
        { value: '益阳', label: '益阳' },
        { value: '郴州', label: '郴州' },
        { value: '永州', label: '永州' },
        { value: '怀化', label: '怀化' },
        { value: '娄底', label: '娄底' },
        { value: '湘西', label: '湘西' }
    ],
    广东: [
        { value: '广州', label: '广州' },
        { value: '韶关', label: '韶关' },
        { value: '深圳', label: '深圳' },
        { value: '珠海', label: '珠海' },
        { value: '汕头', label: '汕头' },
        { value: '佛山', label: '佛山' },
        { value: '江门', label: '江门' },
        { value: '湛江', label: '湛江' },
        { value: '茂名', label: '茂名' },
        { value: '肇庆', label: '肇庆' },
        { value: '惠州', label: '惠州' },
        { value: '梅州', label: '梅州' },
        { value: '汕尾', label: '汕尾' },
        { value: '河源', label: '河源' },
        { value: '阳江', label: '阳江' },
        { value: '清远', label: '清远' },
        { value: '东莞', label: '东莞' },
        { value: '中山', label: '中山' },
        { value: '潮州', label: '潮州' },
        { value: '揭阳', label: '揭阳' },
        { value: '云浮', label: '云浮' }
    ],
    广西: [
        { value: '南宁', label: '南宁' },
        { value: '柳州', label: '柳州' },
        { value: '桂林', label: '桂林' },
        { value: '梧州', label: '梧州' },
        { value: '北海', label: '北海' },
        { value: '防城港', label: '防城港' },
        { value: '钦州', label: '钦州' },
        { value: '贵港', label: '贵港' },
        { value: '玉林', label: '玉林' },
        { value: '百色', label: '百色' },
        { value: '贺州', label: '贺州' },
        { value: '河池', label: '河池' },
        { value: '来宾', label: '来宾' },
        { value: '崇左', label: '崇左' }
    ],
    海南: [
        { value: '海口', label: '海口' },
        { value: '三亚', label: '三亚' },
        { value: '三沙', label: '三沙' },
        { value: '儋州', label: '儋州' }
    ],
    重庆: [
        { value: '万州', label: '万州' },
        { value: '涪陵', label: '涪陵' },
        { value: '渝中', label: '渝中' },
        { value: '大渡口', label: '大渡口' },
        { value: '江北', label: '江北' },
        { value: '沙坪坝', label: '沙坪坝' },
        { value: '九龙坡', label: '九龙坡' },
        { value: '南岸', label: '南岸' },
        { value: '北碚', label: '北碚' },
        { value: '綦江', label: '綦江' },
        { value: '大足', label: '大足' },
        { value: '渝北', label: '渝北' },
        { value: '巴南', label: '巴南' },
        { value: '黔江', label: '黔江' },
        { value: '长寿', label: '长寿' },
        { value: '江津', label: '江津' },
        { value: '合川', label: '合川' },
        { value: '永川', label: '永川' },
        { value: '南川', label: '南川' },
        { value: '璧山', label: '璧山' },
        { value: '铜梁', label: '铜梁' },
        { value: '潼南', label: '潼南' },
        { value: '荣昌', label: '荣昌' },
        { value: '开州', label: '开州' },
        { value: '梁平', label: '梁平' },
        { value: '武隆', label: '武隆' }
    ],
    四川: [
        { value: '成都', label: '成都' },
        { value: '自贡', label: '自贡' },
        { value: '攀枝花', label: '攀枝花' },
        { value: '泸州', label: '泸州' },
        { value: '德阳', label: '德阳' },
        { value: '绵阳', label: '绵阳' },
        { value: '广元', label: '广元' },
        { value: '遂宁', label: '遂宁' },
        { value: '内江', label: '内江' },
        { value: '乐山', label: '乐山' },
        { value: '南充', label: '南充' },
        { value: '眉山', label: '眉山' },
        { value: '宜宾', label: '宜宾' },
        { value: '广安', label: '广安' },
        { value: '达州', label: '达州' },
        { value: '雅安', label: '雅安' },
        { value: '巴中', label: '巴中' },
        { value: '资阳', label: '资阳' },
        { value: '阿坝', label: '阿坝' },
        { value: '甘孜', label: '甘孜' },
        { value: '凉山', label: '凉山' }
    ],
    贵州: [
        { value: '贵阳', label: '贵阳' },
        { value: '六盘水', label: '六盘水' },
        { value: '遵义', label: '遵义' },
        { value: '安顺', label: '安顺' },
        { value: '毕节', label: '毕节' },
        { value: '铜仁', label: '铜仁' },
        { value: '黔西南', label: '黔西南' },
        { value: '黔东南', label: '黔东南' },
        { value: '黔南', label: '黔南' }
    ],
    云南: [
        { value: '昆明', label: '昆明' },
        { value: '曲靖', label: '曲靖' },
        { value: '玉溪', label: '玉溪' },
        { value: '保山', label: '保山' },
        { value: '昭通', label: '昭通' },
        { value: '丽江', label: '丽江' },
        { value: '普洱', label: '普洱' },
        { value: '临沧', label: '临沧' },
        { value: '楚雄', label: '楚雄' },
        { value: '红河', label: '红河' },
        { value: '文山', label: '文山' },
        { value: '西双版纳', label: '西双版纳' },
        { value: '大理', label: '大理' },
        { value: '德宏', label: '德宏' },
        { value: '怒江', label: '怒江' },
        { value: '迪庆', label: '迪庆' }
    ],
    西藏: [
        { value: '拉萨', label: '拉萨' },
        { value: '日喀则', label: '日喀则' },
        { value: '昌都', label: '昌都' },
        { value: '林芝', label: '林芝' },
        { value: '山南', label: '山南' },
        { value: '那曲', label: '那曲' },
        { value: '阿里', label: '阿里' }
    ],
    陕西: [
        { value: '西安', label: '西安' },
        { value: '铜川', label: '铜川' },
        { value: '宝鸡', label: '宝鸡' },
        { value: '咸阳', label: '咸阳' },
        { value: '渭南', label: '渭南' },
        { value: '延安', label: '延安' },
        { value: '汉中', label: '汉中' },
        { value: '榆林', label: '榆林' },
        { value: '安康', label: '安康' },
        { value: '商洛', label: '商洛' }
    ],
    甘肃: [
        { value: '兰州', label: '兰州' },
        { value: '嘉峪关', label: '嘉峪关' },
        { value: '金昌', label: '金昌' },
        { value: '白银', label: '白银' },
        { value: '天水', label: '天水' },
        { value: '武威', label: '武威' },
        { value: '张掖', label: '张掖' },
        { value: '平凉', label: '平凉' },
        { value: '酒泉', label: '酒泉' },
        { value: '庆阳', label: '庆阳' },
        { value: '定西', label: '定西' },
        { value: '陇南', label: '陇南' },
        { value: '临夏', label: '临夏' },
        { value: '甘南', label: '甘南' }
    ],
    青海: [
        { value: '西宁', label: '西宁' },
        { value: '海东', label: '海东' },
        { value: '海北', label: '海北' },
        { value: '黄南', label: '黄南' },
        { value: '海南', label: '海南' },
        { value: '果洛', label: '果洛' },
        { value: '玉树', label: '玉树' },
        { value: '海西', label: '海西' }
    ],
    宁夏: [
        { value: '银川', label: '银川' },
        { value: '石嘴山', label: '石嘴山' },
        { value: '吴忠', label: '吴忠' },
        { value: '固原', label: '固原' },
        { value: '中卫', label: '中卫' }
    ],
    新疆: [
        { value: '乌鲁木齐', label: '乌鲁木齐' },
        { value: '克拉玛依', label: '克拉玛依' },
        { value: '吐鲁番', label: '吐鲁番' },
        { value: '哈密', label: '哈密' },
        { value: '昌吉', label: '昌吉' },
        { value: '博尔塔拉', label: '博尔塔拉' },
        { value: '巴音郭楞', label: '巴音郭楞' },
        { value: '阿克苏', label: '阿克苏' },
        { value: '克孜勒苏', label: '克孜勒苏' },
        { value: '喀什', label: '喀什' },
        { value: '和田', label: '和田' },
        { value: '伊犁', label: '伊犁' },
        { value: '塔城', label: '塔城地' },
        { value: '阿勒泰', label: '阿勒泰' }
    ],
    台湾: [
        { value: '台北', label: '台北' },
        { value: '高雄', label: '高雄' },
        { value: '基隆', label: '基隆' },
        { value: '台中', label: '台中' },
        { value: '台南', label: '台南' },
        { value: '新竹', label: '新竹' },
        { value: '嘉义', label: '嘉义' },
        { value: '台北县', label: '台北县' },
        { value: '宜兰县', label: '宜兰县' },
        { value: '桃园县', label: '桃园县' },
        { value: '新竹县', label: '新竹县' },
        { value: '苗栗县', label: '苗栗县' },
        { value: '台中县', label: '台中县' },
        { value: '彰化县', label: '彰化县' },
        { value: '南投县', label: '南投县' },
        { value: '云林县', label: '云林县' },
        { value: '嘉义县', label: '嘉义县' },
        { value: '台南县', label: '台南县' },
        { value: '高雄县', label: '高雄县' },
        { value: '屏东县', label: '屏东县' },
        { value: '台东县', label: '台东县' },
        { value: '花莲县', label: '花莲县' },
        { value: '澎湖县', label: '澎湖县' }
    ],
    香港: [
        { value: '中西区', label: '中西区' },
        { value: '湾仔', label: '湾仔' },
        { value: '东区', label: '东区' },
        { value: '南区', label: '南区' },
        { value: '油尖旺', label: '油尖旺' },
        { value: '深水埗', label: '深水埗' },
        { value: '九龙城', label: '九龙城' },
        { value: '黄大仙', label: '黄大仙' },
        { value: '观塘', label: '观塘' },
        { value: '荃湾', label: '荃湾' },
        { value: '屯门', label: '屯门' },
        { value: '元朗', label: '元朗' },
        { value: '北区', label: '北区' },
        { value: '大埔', label: '大埔' },
        { value: '西贡', label: '西贡' },
        { value: '沙田', label: '沙田' },
        { value: '葵青', label: '葵青' },
        { value: '离岛', label: '离岛' }
    ],
    澳门: [
        { value: '花地玛堂', label: '花地玛堂' },
        { value: '花王堂', label: '花王堂' },
        { value: '望德堂', label: '望德堂' },
        { value: '大堂', label: '大堂' },
        { value: '风顺堂', label: '风顺堂' },
        { value: '嘉模堂', label: '嘉模堂' },
        { value: '路凼填海', label: '路凼填海' },
        { value: '圣方济各堂', label: '圣方济各堂' },
        { value: '氹仔', label: '氹仔' }
    ]
}
